GET http://localhost:3000/products


### create a product

POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"I Mac Pro ",
   "price":"5000",
  "available":"10" 
}

### get a product by id
GET http://localhost:3000/products/61cbefa8ea08aa9d6b3e8359

### Update a product by id
PATCH http://localhost:3000/products/61c95b3c232d74122aefaa78
Content-Type: application/json

{
 
  "price":9999
}


### Delete a product by id
DELETE http://localhost:3000/products/61d022aad1dc862048ce1d1g
###

GET http://localhost:3000/abc

###


GET http://localhost:3000/test?name=iMac&price=3000

###
GET http://localhost:3000/test/9876543001/imac

###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name":"ImacPro",
    "price":"3999",
    "available":"13"
}
