GET http://localhost:3000/products


### create a product

POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"IPhone 11",
  "price":"6499",
  "available":"8" 
}

### get a product by id
GET http://localhost:3000/products/id 

### Update a product by id
PATCH http://localhost:3000/products/id


### Delete a product by id
DELETE http://localhost:3000/products/id
###

GET http://localhost:3000/abc

###


GET http://localhost:3000/test?name=iMac&price=3000

###
GET http://localhost:3000/test/9876543001/imac

###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name":"ImacPro",
    "price":"3999",
    "available":"13"
}
